remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Hi, I'm Linoy
description: I'm a machine learning engineer, exploring the world of AI & arts one diffusion step at a time
